# Generated by Django 3.2.4 on 2021-07-09 02:16
# 내용을 이해할 필요는 없으나 지우면 문제가 생김(변화를 반영하기에 DB에 문제가 생김, DB를 밀어버릴 때만!!)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
